
#line 3 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 0
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart(yyin  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern yy_size_t yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    #define YY_LESS_LINENO(n)
    #define YY_LINENO_REWIND_TO(ptr)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = 0; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
yy_size_t yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart (FILE *input_file  );
void yy_switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer (FILE *file,int size  );
void yy_delete_buffer (YY_BUFFER_STATE b  );
void yy_flush_buffer (YY_BUFFER_STATE b  );
void yypush_buffer_state (YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state (void );

static void yyensure_buffer_stack (void );
static void yy_load_buffer_state (void );
static void yy_init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER yy_flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer (char *base,yy_size_t size  );
YY_BUFFER_STATE yy_scan_string (yyconst char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes (yyconst char *bytes,yy_size_t len  );

void *yyalloc (yy_size_t  );
void *yyrealloc (void *,yy_size_t  );
void yyfree (void *  );

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

typedef unsigned char YY_CHAR;

FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;

typedef int yy_state_type;

extern int yylineno;

int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state (void );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  );
static int yy_get_next_buffer (void );
#if defined(__GNUC__) && __GNUC__ >= 3
__attribute__((__noreturn__))
#endif
static void yy_fatal_error (yyconst char msg[]  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;

#define YY_NUM_RULES 18
#define YY_END_OF_BUFFER 19
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[284] =
    {   0,
        0,    0,   19,   18,   18,   18,   18,    9,   14,   14,
       14,   17,   17,   17,   17,   13,   17,   17,   17,   17,
       17,   17,   17,    0,    0,    0,   11,    9,    0,    9,
       15,   14,    0,    2,    0,   17,    0,   17,   17,   17,
       17,   17,   17,   17,   17,   17,   13,   17,   17,    0,
       10,    0,    0,    0,    0,    0,    0,    0,    0,   17,
       17,   17,   17,   17,   17,   17,   17,   17,   13,   17,
       17,    0,    0,    0,    0,    0,    0,   17,   17,   17,
       17,   17,   17,   17,   17,   17,   17,   17,   17,   17,
       17,   16,    0,    0,    0,    0,    0,   12,   17,   17,

        0,   17,   17,   17,   17,   17,   17,   17,   17,    0,
        0,   17,   17,    0,    0,    0,    7,    0,   17,   17,
        0,    0,    0,    5,    5,    5,    5,   17,   17,   17,
       17,   17,   17,   17,   17,    0,    0,    0,    0,    0,
        0,    0,   17,   17,    0,    5,    5,    0,    5,    5,
        5,   17,   17,   17,   17,   17,    8,   17,    0,    1,
        0,    0,    0,    0,    0,    0,    0,   17,   17,    5,
        5,    5,    0,    0,    0,    0,   17,   17,   17,   17,
       17,    0,    0,    0,   17,    5,    5,    0,    0,    0,
        0,    0,    0,    0,   17,   17,    8,   17,    0,    0,

        0,    5,    5,    0,    4,    0,    0,    0,    0,    0,
        0,    0,    0,    0,   17,   17,    6,    0,    5,    0,
        0,    0,    0,    0,    0,    0,    0,    0,   17,   17,
        0,    5,    0,    2,    0,    2,    0,    0,    0,    0,
       17,    0,    0,    5,    2,    2,    0,    3,    0,    3,
       17,    0,    0,    5,    3,    3,   17,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    7,    0,    0,    0,    0,    0,
        0,    0,    0
    } ;

static yyconst YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    1,    3,    1,    1,    1,    1,    1,    4,
        5,    1,    1,    6,    7,    8,    1,    9,    9,    9,
        9,    9,    9,    9,    9,    9,    9,   10,    1,   11,
       12,   13,    1,    1,   14,   15,   15,   16,   17,   18,
       15,   15,   19,   15,   15,   20,   15,   15,   21,   15,
       15,   22,   23,   15,   15,   24,   15,   15,   15,   15,
       25,    1,   26,    1,   27,    1,   28,   15,   29,   30,

       31,   32,   33,   34,   35,   15,   15,   36,   37,   38,
       39,   40,   15,   41,   42,   43,   44,   45,   15,   46,
       15,   15,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst YY_CHAR yy_meta[47] =
    {   0,
        1,    2,    3,    1,    4,    5,    6,    1,    7,    8,
        1,    1,    1,    9,    9,    9,    9,    9,    9,    9,
        9,    9,    9,    9,    1,    1,   10,    9,    9,    9,
        9,    9,    9,    9,    9,    9,    9,    9,    9,    9,
        9,    9,    9,    9,    9,    9
    } ;

static yyconst flex_uint16_t yy_base[309] =
    {   0,
        0,    0,  798, 1019,  795,  792,  785,   39,   42, 1019,
      781,   51,   57,   63,   72,   79,   81,   88,   97,   99,
      108,  127,  129,  790,   86,  784, 1019,  776,  773,   42,
     1019, 1019,  109, 1019,  777,  136,  115,  143,  159,  165,
      172,  174,  181,  183,  190,  192,  203,  210,  220,  226,
      754,  760,  227,  212,  726,  713,  710,  717,  708,  249,
      260,  269,  275,  281,  321,  212,  261,  267,  272,  277,
      293,  309,  697,  693,  696,  696,  672,  307,  323,  328,
      338,  340,  334,  339,  341,  354,  356,  371,  403,  410,
      412,  419,  685,  678,  673,  671,  665,  421,  428,  430,

      472,  443,  450,  452,  459,  461,  481,  487,  496,  466,
      701,  502,  508,  673,  663,  667, 1019,  651,  514,  361,
      540,  687,  677,   67,    0,  670,  663,  504,  520,  531,
      537,  550,  552,  557,  563,  676,  118,  528,  631,  631,
      627,   70,  568,  573,  660, 1019,  650,  645,    0,  628,
      611,  523,  605,  614,  616,  597,  599,  604,  120, 1019,
      138,  632,  595,  586,  573,  122,  597,  618,  625,  589,
      570,  559,  641,  572,  658,  152,  665,  671,  677,  683,
      689,  531,  531,  164,  695,  546,  552,  559,  157,  201,
      553,   58,  708,  232,  715,  695,  700,  702,  516,  523,

      545,    0,  529,  237, 1019,  256,  537,   64,  106,  247,
      215,  265,  536,  254,  713,  715, 1019,  514,  504,  267,
      515,  375,  512,  508,  276,  282,  388,  288,  728,  733,
      304,  490,  503,    0,  500,  498,  330,  492,  439,  481,
      738,  104,  197,  458,    0,  457,  448,    0,  444,  444,
      743,  398,  412,  416,    0,  417,  749,  755,  770,  382,
      366,  356,  349,  323,  315,  308,  306,  288,  279,  261,
      227,  216,  184,  181, 1019,  147,  125,  118,   66,   40,
       17,   21, 1019,  810,  819,  828,  837,  846,  854,  863,
      871,  880,  884,  893,  902,  910,  918,  928,  937,  946,

      955,  964,  973,  982,  986,  995, 1004, 1008
    } ;

static yyconst flex_int16_t yy_def[309] =
    {   0,
      283,    1,  283,  283,  284,  285,  283,  283,  283,  283,
      283,  286,  286,  286,  286,  286,  286,  286,  286,  286,
      286,  286,  286,  284,  287,  285,  283,  283,  283,  283,
      283,  283,  283,  283,  288,  286,  283,  286,  286,  286,
      286,  286,  286,  286,  286,  286,  286,  286,  286,  287,
      283,  288,  289,  283,  283,  283,  283,  283,  283,  286,
      286,  286,  286,  286,  286,   65,   65,   65,   65,   65,
       65,  289,  283,  283,  283,  283,  283,   65,   65,   65,
      286,  286,   65,   65,   65,   65,   65,   65,  286,  286,
      286,  286,  283,  283,  283,  283,  283,  286,  286,  286,

      290,  286,  286,  286,  286,  286,  286,  286,  286,  283,
      291,  286,  286,  283,  283,  283,  283,  283,  286,   65,
      290,  292,  283,  283,  293,  293,  293,   65,   65,   65,
       65,   65,   65,   65,   65,  291,  294,  283,  283,  283,
      283,  283,   65,   65,  292,  283,  283,  283,  293,  293,
      293,  286,  286,  286,  286,   65,   65,   65,  283,  283,
      294,  283,  283,  283,  283,  283,  283,   65,   65,  283,
      293,  293,  283,  295,  283,  296,  286,  286,  286,  286,
      286,  283,  283,  283,  286,  293,  293,  295,  297,  296,
      298,  299,  283,  300,  286,   65,   65,   65,  283,  283,

      283,  293,  293,  283,  283,  297,  298,  283,  283,  283,
      299,  300,  301,  302,   65,   65,  283,  283,  293,  283,
      303,  283,  304,  301,  283,  283,  283,  302,   65,   65,
      283,  293,  303,  305,  304,  283,  283,  306,  283,  307,
       65,  283,  283,  293,  305,  283,  306,  308,  307,  283,
       65,  283,  283,  293,  308,  283,   65,  283,  283,  283,
      283,  283,  283,  283,  283,  283,  283,  283,  283,  283,
      283,  283,  283,  283,  283,  283,  283,  283,  283,  283,
      283,  283,    0,  283,  283,  283,  283,  283,  283,  283,
      283,  283,  283,  283,  283,  283,  283,  283,  283,  283,

      283,  283,  283,  283,  283,  283,  283,  283
    } ;

static yyconst flex_uint16_t yy_nxt[1066] =
    {   0,
        4,    5,    6,    4,    4,    4,    7,    4,    8,    4,
        9,   10,   11,   12,   12,   12,   12,   13,   12,   12,
       12,   12,   12,   14,    4,    4,    4,   12,   15,   12,
       16,   17,   12,   12,   18,   19,   12,   20,   21,   12,
       22,   12,   12,   12,   12,   23,   29,   30,   31,   29,
       30,  275,   33,   32,   32,   34,   35,  282,   33,  209,
       37,   34,   35,  210,   33,  220,   37,   34,   35,  221,
       38,  166,   37,   33,  148,  124,   34,   35,  275,   39,
       33,   37,   33,   34,   35,   34,   35,   33,   37,   33,
       37,   35,   34,   35,  167,   37,  281,   37,   33,   40,

       33,   34,   35,   34,   35,  242,   37,  209,   37,   33,
       33,  210,   34,   35,   35,   42,   54,   37,   37,  159,
       41,  159,  160,  166,  160,   43,   46,   44,   33,  243,
       33,   34,   35,   34,   35,   45,   37,   33,   37,  159,
       34,   35,  160,   55,   33,   37,  167,   34,   35,   56,
       57,   47,   37,  190,  191,   58,  275,   48,  204,   59,
       33,  205,   60,   34,   35,  280,   33,   49,   37,   34,
       35,  201,  184,   33,   37,   33,   34,   35,   34,   35,
       61,   37,   33,   37,   33,   34,   35,   34,   35,  279,
       37,   33,   37,   33,   34,   35,   34,   35,  252,   37,

       64,   37,  190,  191,   33,   62,   63,   34,   35,  278,
       65,   33,   37,   54,   34,   35,  209,   67,  277,   37,
      210,   33,   68,   66,   34,   35,  253,   33,   33,   37,
       69,   35,   35,  212,  213,   37,   37,   71,  204,   36,
       55,  205,   88,   36,  276,   70,   56,   57,  222,  223,
       33,   36,   58,   34,   35,  226,   59,  204,   37,  227,
      205,   33,  275,   69,   34,   35,  212,  213,  220,   37,
       33,   78,  221,   34,   35,   79,   33,  237,   37,   34,
       35,  238,   33,  226,   37,   34,   35,  227,   89,  226,
       37,   36,   36,  227,   36,  274,   80,   36,   36,   36,

       36,   90,   36,   36,   36,  242,   36,   36,   36,  273,
       33,   36,  231,   81,   35,  272,   36,   91,   37,   82,
       36,   83,   33,   36,   36,   34,   35,   98,   92,  243,
       37,  237,   36,  271,   36,  238,   99,   36,   36,  101,
      270,   33,   34,   35,   34,   35,   36,   37,   84,   37,
       36,   85,   86,   36,   36,   36,  100,  269,   36,   36,
       87,   36,   36,  268,  103,   36,   36,   36,   36,   36,
       36,   36,   36,   36,  104,  102,  222,  223,   36,  267,
       36,   36,  105,  107,   36,   36,   36,   36,   36,  239,
      240,  144,   36,   36,  266,   36,  108,  106,   36,  252,

       36,   36,   36,  265,  110,  109,  111,   34,   35,  264,
       36,   33,   37,   33,   34,   35,   34,   35,  256,   37,
       33,   37,   33,   34,   35,   34,   35,  253,   37,   33,
       37,   33,   34,   35,   34,   35,  202,   37,  112,   37,
      239,  240,  258,  119,   33,  256,  250,   34,   35,  247,
      113,   33,   37,   33,   34,   35,   34,   35,  246,   37,
       33,   37,   33,   34,   35,   34,   35,  110,   37,  111,
       37,   35,  120,  121,  122,   37,  128,   35,  123,  254,
      124,   37,   33,  250,  130,   34,   35,  131,   33,  126,
       37,   34,   35,  247,  129,  127,   37,   33,  132,  246,

       34,   35,  236,   33,  233,   37,   34,   35,  244,  138,
      225,   37,   34,   35,  236,   33,  233,   37,   34,   35,
      232,  133,  231,   37,  173,  134,  174,   34,   35,  162,
      143,  152,   37,   35,   36,   36,  135,   37,  225,  208,
       92,  121,  122,   36,  219,   35,  123,  153,  124,   37,
       36,   36,  218,  117,  217,  208,  163,  126,   36,   36,
      188,   36,   36,  127,   36,  203,  202,   36,   36,  154,
       36,  200,  199,  188,  187,  155,   36,   36,  156,  157,
       36,   36,   36,   36,   36,  158,  168,   36,   36,   36,
       36,   36,  186,   36,   36,   36,   36,  170,   36,   36,

       36,   92,   36,   36,   36,  184,  175,   36,  176,   34,
       35,  117,   36,  169,   37,   33,  183,   33,   34,   35,
       34,   35,  182,   37,  180,   37,   36,   36,   36,   36,
       36,   36,  172,  162,  181,   36,   36,   35,   36,  185,
      177,   37,  173,   36,  174,   36,   35,  171,   36,   36,
       37,  179,   36,  170,  178,   92,   36,   36,  147,  175,
      163,  176,  146,   35,   36,  117,  193,   37,  194,   34,
       35,  165,   33,  164,   37,   34,   35,  136,   33,  151,
       37,   34,   35,  150,   33,  147,   37,   34,   35,  146,
       33,  142,   37,   34,   35,  141,   33,  140,   37,   34,

       35,  139,  136,  118,   37,  195,  117,  116,  115,  193,
      196,  194,  114,   35,   97,   98,   33,   37,  198,   34,
       35,  197,  197,   96,   37,   36,   36,   36,   95,   36,
       36,   36,   36,   36,   36,   94,  216,   93,   77,   36,
       36,   36,   36,   36,   36,   36,   36,   76,   75,  229,
       74,  230,   36,   73,   36,   36,  259,  215,   36,   36,
       36,   52,   51,  241,   36,   36,  197,   36,   36,   36,
       36,  259,   36,   36,   36,  251,   36,   36,   52,   36,
       36,   51,   36,  260,   28,  257,   27,  197,   36,  261,
      262,   24,   32,   28,   27,  263,   24,  283,  260,  283,

      283,  283,  283,  283,  261,  262,  283,  283,  283,  283,
      263,   25,  283,  283,  283,  283,  283,  283,   25,   26,
       26,   26,   26,   26,   26,   26,   26,   26,   26,   36,
      283,   36,   36,  283,   36,   36,   36,   36,   50,  283,
      283,   50,  283,   50,   50,   50,   50,   53,  283,  283,
      283,  283,  283,  283,   53,   72,  283,  283,   72,  283,
       72,   72,   72,   72,  125,  125,  283,  125,  125,  125,
      125,  125,  137,  283,  283,  283,  283,  283,  283,  137,
      145,  145,  145,  145,  145,  145,  145,  145,  145,  145,
      149,  283,  149,  149,  161,  283,  161,  283,  283,  161,

      283,  161,  161,  189,  283,  283,  283,  283,  283,  283,
      189,  192,  192,  283,  283,  283,  283,  283,  192,  206,
      283,  206,  283,  283,  206,  283,  206,  206,  207,  207,
      207,  207,  207,  207,  207,  207,  207,  207,  211,  283,
      283,  211,  283,  211,  283,  211,  211,  214,  214,  283,
      283,  283,  283,  283,  214,  224,  224,  224,  224,  224,
      224,  224,  224,  224,  224,  228,  283,  283,  228,  283,
      228,  283,  228,  228,  234,  283,  283,  283,  283,  283,
      283,  234,  235,  235,  235,  235,  235,  235,  235,  235,
      235,  235,  245,  283,  245,  245,  248,  283,  283,  283,

      283,  283,  283,  248,  249,  249,  249,  249,  249,  249,
      249,  249,  249,  249,  255,  283,  255,  255,    3,  283,
      283,  283,  283,  283,  283,  283,  283,  283,  283,  283,
      283,  283,  283,  283,  283,  283,  283,  283,  283,  283,
      283,  283,  283,  283,  283,  283,  283,  283,  283,  283,
      283,  283,  283,  283,  283,  283,  283,  283,  283,  283,
      283,  283,  283,  283,  283
    } ;

static yyconst flex_int16_t yy_chk[1066] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    8,    8,    9,   30,
       30,  282,   12,    9,    9,   12,   12,  281,   13,  192,
       12,   13,   13,  192,   14,  208,   13,   14,   14,  208,
       13,  142,   14,   15,  124,  124,   15,   15,  280,   14,
       16,   15,   17,   16,   16,   17,   17,   25,   16,   18,
       17,   25,   18,   18,  142,   25,  279,   18,   19,   15,

       20,   19,   19,   20,   20,  242,   19,  209,   20,   21,
       33,  209,   21,   21,   33,   17,   37,   21,   33,  137,
       16,  159,  137,  166,  159,   18,   20,   19,   22,  242,
       23,   22,   22,   23,   23,   19,   22,   36,   23,  161,
       36,   36,  161,   37,   38,   36,  166,   38,   38,   37,
       37,   21,   38,  176,  176,   37,  278,   22,  189,   37,
       39,  189,   38,   39,   39,  277,   40,   23,   39,   40,
       40,  184,  184,   41,   40,   42,   41,   41,   42,   42,
       39,   41,   43,   42,   44,   43,   43,   44,   44,  276,
       43,   45,   44,   46,   45,   45,   46,   46,  243,   45,

       41,   46,  190,  190,   47,   40,   40,   47,   47,  274,
       42,   48,   47,   54,   48,   48,  211,   44,  273,   48,
      211,   49,   45,   43,   49,   49,  243,   50,   53,   49,
       46,   50,   53,  194,  194,   50,   53,   48,  204,   66,
       54,  204,   66,   66,  272,   47,   54,   54,  210,  210,
       60,   66,   54,   60,   60,  214,   54,  206,   60,  214,
      206,   61,  271,   49,   61,   61,  212,  212,  220,   61,
       62,   60,  220,   62,   62,   61,   63,  225,   62,   63,
       63,  225,   64,  226,   63,   64,   64,  226,   67,  228,
       64,   67,   67,  228,   68,  270,   62,   68,   68,   69,

       67,   68,   69,   69,   70,  231,   68,   70,   70,  269,
       72,   69,  231,   63,   72,  268,   70,   70,   72,   64,
       71,   64,   65,   71,   71,   65,   65,   78,   71,  231,
       65,  237,   71,  267,   78,  237,   79,   78,   78,   81,
      266,   82,   81,   81,   82,   82,   78,   81,   65,   82,
       79,   65,   65,   79,   79,   80,   80,  265,   80,   80,
       65,   83,   79,  264,   83,   83,   84,   80,   85,   84,
       84,   85,   85,   83,   84,   82,  222,  222,   84,  263,
       85,   86,   85,   87,   86,   86,   87,   87,  120,  227,
      227,  120,  120,   86,  262,   87,   87,   86,   88,  252,

      120,   88,   88,  261,   89,   88,   89,   89,   89,  260,
       88,   90,   89,   91,   90,   90,   91,   91,  256,   90,
       92,   91,   98,   92,   92,   98,   98,  252,   92,   99,
       98,  100,   99,   99,  100,  100,  254,   99,   90,  100,
      239,  239,  253,   99,  102,  250,  249,  102,  102,  247,
       91,  103,  102,  104,  103,  103,  104,  104,  246,  103,
      105,  104,  106,  105,  105,  106,  106,  110,  105,  110,
      106,  110,  100,  101,  101,  110,  102,  101,  101,  244,
      101,  101,  107,  240,  104,  107,  107,  105,  108,  101,
      107,  108,  108,  238,  103,  101,  108,  109,  106,  236,

      109,  109,  235,  112,  233,  109,  112,  112,  232,  113,
      224,  112,  113,  113,  223,  119,  221,  113,  119,  119,
      219,  107,  218,  119,  152,  108,  152,  152,  152,  138,
      119,  128,  152,  138,  128,  128,  109,  138,  213,  207,
      112,  121,  121,  128,  203,  121,  121,  129,  121,  121,
      129,  129,  201,  200,  199,  191,  138,  121,  130,  129,
      188,  130,  130,  121,  131,  187,  186,  131,  131,  130,
      130,  183,  182,  174,  172,  131,  131,  132,  132,  133,
      132,  132,  133,  133,  134,  134,  143,  134,  134,  132,
      135,  133,  171,  135,  135,  143,  134,  170,  143,  143,

      144,  135,  135,  144,  144,  167,  153,  143,  153,  153,
      153,  165,  144,  144,  153,  154,  164,  155,  154,  154,
      155,  155,  163,  154,  156,  155,  157,  156,  156,  157,
      157,  158,  151,  162,  158,  158,  156,  162,  157,  168,
      153,  162,  173,  158,  173,  168,  173,  150,  168,  168,
      173,  155,  169,  148,  154,  169,  169,  168,  147,  175,
      162,  175,  145,  175,  169,  141,  177,  175,  177,  177,
      177,  140,  178,  139,  177,  178,  178,  136,  179,  127,
      178,  179,  179,  126,  180,  123,  179,  180,  180,  122,
      181,  118,  180,  181,  181,  116,  185,  115,  181,  185,

      185,  114,  111,   97,  185,  178,   96,   95,   94,  193,
      179,  193,   93,  193,   77,  185,  195,  193,  181,  195,
      195,  180,  196,   76,  195,  196,  196,  197,   75,  198,
      197,  197,  198,  198,  196,   74,  198,   73,   59,  197,
      215,  198,  216,  215,  215,  216,  216,   58,   57,  215,
       56,  216,  215,   55,  216,  229,  258,  195,  229,  229,
      230,   52,   51,  230,  230,  241,  229,  229,  241,  241,
      251,  259,  230,  251,  251,  241,  257,  241,   35,  257,
      257,   29,  251,  258,   28,  251,   26,  257,  257,  258,
      258,   24,   11,    7,    6,  258,    5,    3,  259,    0,

        0,    0,    0,    0,  259,  259,    0,    0,    0,    0,
      259,  284,    0,    0,    0,    0,    0,    0,  284,  285,
      285,  285,  285,  285,  285,  285,  285,  285,  285,  286,
        0,  286,  286,    0,  286,  286,  286,  286,  287,    0,
        0,  287,    0,  287,  287,  287,  287,  288,    0,    0,
        0,    0,    0,    0,  288,  289,    0,    0,  289,    0,
      289,  289,  289,  289,  290,  290,    0,  290,  290,  290,
      290,  290,  291,    0,    0,    0,    0,    0,    0,  291,
      292,  292,  292,  292,  292,  292,  292,  292,  292,  292,
      293,    0,  293,  293,  294,    0,  294,    0,    0,  294,

        0,  294,  294,  295,    0,    0,    0,    0,    0,    0,
      295,  296,  296,    0,    0,    0,    0,    0,  296,  297,
        0,  297,    0,    0,  297,    0,  297,  297,  298,  298,
      298,  298,  298,  298,  298,  298,  298,  298,  299,    0,
        0,  299,    0,  299,    0,  299,  299,  300,  300,    0,
        0,    0,    0,    0,  300,  301,  301,  301,  301,  301,
      301,  301,  301,  301,  301,  302,    0,    0,  302,    0,
      302,    0,  302,  302,  303,    0,    0,    0,    0,    0,
        0,  303,  304,  304,  304,  304,  304,  304,  304,  304,
      304,  304,  305,    0,  305,  305,  306,    0,    0,    0,

        0,    0,    0,  306,  307,  307,  307,  307,  307,  307,
      307,  307,  307,  307,  308,    0,  308,  308,  283,  283,
      283,  283,  283,  283,  283,  283,  283,  283,  283,  283,
      283,  283,  283,  283,  283,  283,  283,  283,  283,  283,
      283,  283,  283,  283,  283,  283,  283,  283,  283,  283,
      283,  283,  283,  283,  283,  283,  283,  283,  283,  283,
      283,  283,  283,  283,  283
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "portugolToC.l"
/**********	Definições *********/
/* Operadores artiméticos */
/* Operadores de caracteres */
/* Operadores relacionais */
/* Operadores lógicos */
/* Comando de atribuição */
/* Cabeçalhos */
/* Declaração de variáveis */
/* Função e procedimento */
/*funcao, fimfuncao, procedimento, fimprocedimento, retorne, var*/
/** Cabeçalhos */
/* algoritmo, fimalgoritmo, var, inicio (fim do var) */
/********** FIM	Definições *********/
#line 810 "lex.yy.c"

#define INITIAL 0

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals (void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy (void );

int yyget_debug (void );

void yyset_debug (int debug_flag  );

YY_EXTRA_TYPE yyget_extra (void );

void yyset_extra (YY_EXTRA_TYPE user_defined  );

FILE *yyget_in (void );

void yyset_in  (FILE * _in_str  );

FILE *yyget_out (void );

void yyset_out  (FILE * _out_str  );

yy_size_t yyget_leng (void );

char *yyget_text (void );

int yyget_lineno (void );

void yyset_lineno (int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap (void );
#else
extern int yywrap (void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput (int c,char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (void );
#else
static int input (void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, yyin))==0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer(yyin,YY_BUF_SIZE );
		}

		yy_load_buffer_state( );
		}

	{
#line 64 "portugolToC.l"


#line 1031 "lex.yy.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 284 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 1019 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 66 "portugolToC.l"
{printf("leia var\n");}
	YY_BREAK
case 2:
/* rule 2 can match eol */
YY_RULE_SETUP
#line 68 "portugolToC.l"
{printf("escreva\n");}
	YY_BREAK
case 3:
/* rule 3 can match eol */
YY_RULE_SETUP
#line 69 "portugolToC.l"
{printf("escreval\n");}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 71 "portugolToC.l"
{printf("escolha\n");}
	YY_BREAK
case 5:
/* rule 5 can match eol */
YY_RULE_SETUP
#line 72 "portugolToC.l"
{printf("caso\n");}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 73 "portugolToC.l"
{printf("outro caso\n");}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 75 "portugolToC.l"
{printf("Declarou variaveis");}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 76 "portugolToC.l"
{printf("Fim do bloco");}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 78 "portugolToC.l"
{printf("inteiro\n");}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 79 "portugolToC.l"
{printf("real\n");}
	YY_BREAK
case 11:
/* rule 11 can match eol */
YY_RULE_SETUP
#line 80 "portugolToC.l"
{printf("string\n");}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 81 "portugolToC.l"
{printf("logico\n");}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 82 "portugolToC.l"
{printf("operador logico\n");}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 83 "portugolToC.l"
{printf("operador relacional\n");}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 84 "portugolToC.l"
{printf("recebe\n");}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 85 "portugolToC.l"
{printf("tipo de variavel");}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 86 "portugolToC.l"
{printf("identificador: %s\n", yytext);}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 90 "portugolToC.l"
ECHO;
	YY_BREAK
#line 1182 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	yy_size_t number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (yy_size_t) ((yy_c_buf_p) - (yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			yy_size_t num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				yy_size_t new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc((void *) b->yy_ch_buf,b->yy_buf_size + 2  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart(yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((int) ((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 284 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 284 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 283);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		yy_size_t number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			yy_size_t offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart(yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap( ) )
						return EOF;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer(yyin,YY_BUF_SIZE );
	}

	yy_init_buffer(YY_CURRENT_BUFFER,input_file );
	yy_load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = (yy_size_t)size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree((void *) b->yy_ch_buf  );

	yyfree((void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );
								  
		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (yyconst char * yystr )
{
    
	return yy_scan_bytes(yystr,strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (yyconst char * yybytes, yy_size_t  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	yy_size_t i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) yyalloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg )
{
			(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
        
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
yy_size_t yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = 0;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = (char *) 0;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = (FILE *) 0;
    yyout = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return (void *) malloc( size );
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 90 "portugolToC.l"


int main(int argc, char **argv)
{
yylex();
}

